# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            We Are Wired In
tagline:          A modern productivity tool for Mac, iOS & your desk.
url:              http://blog.wearewired.in
paginate:         1
baseurl:          /
author:
  name:           Wired In
  url:            https://twitter.com/wearewiredin
  email:          hello@wearewired.in

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
